### ISSUE TITLE
设置俩个平行的数据的时候，两边同时滑动出现问题

### ISSUE THREAD

**Issue by 867588763** [weidongjian/androidWheelView#35]
错误信息：
07-13 10:52:02.907 16432-16432/io.dcloud.H53E50BCA E/InputEventReceiver: Exception dispatching input event.
07-13 10:52:02.907 16432-16432/io.dcloud.H53E50BCA E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-13 10:52:02.909 16432-16432/io.dcloud.H53E50BCA E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
                                                                           at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                           at android.view.MotionEvent.getX(MotionEvent.java:2139)
                                                                           at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:3125)
                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                           at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
                                                                           at android.view.View.dispatchPointerEvent(View.java:10248)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4511)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4379)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3921)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3974)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3940)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4067)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3948)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4124)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3921)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3974)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3940)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3948)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3921)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6326)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6300)
                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6261)
                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6429)
                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                           at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                           at android.os.Looper.loop(Looper.java:139)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6252)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
07-13 10:52:02.909 16432-16432/io.dcloud.H53E50BCA D/AndroidRuntime: Shutting down VM
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err: java.lang.IllegalArgumentException: pointerIndex out of range
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.MotionEvent.nativeGetAxisValue(Native Method)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.MotionEvent.getX(MotionEvent.java:2139)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.910 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3125)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.View.dispatchPointerEvent(View.java:10248)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4511)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4379)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3921)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3974)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3940)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4067)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3948)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4124)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3921)
07-13 10:52:02.911 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3974)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3940)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3948)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3921)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6326)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6300)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6261)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6429)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:323)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.os.Looper.loop(Looper.java:139)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6252)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
07-13 10:52:02.912 16432-16432/io.dcloud.H53E50BCA W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
07-13 10:52:03.670 8098-8098/? W/g.zlms.lms:cmf]: type=1400 audit(0.0:168573): avc: denied { ioctl } for path="socket:[14573011]" dev="sockfs" ino=14573011 ioctlcmd=8927 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=tcp_socket permissive=0

 下面是我的代码
        <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/type_wheel_top_layout"
            android:weightSum="2" >

            <com.weigan.loopview.LoopView
                android:id="@+id/pur_wv_type"
                android:layout_width="match_parent"
                android:layout_height="160dp"
                android:layout_marginLeft="6dip"
                android:layout_weight="1" />

            <com.weigan.loopview.LoopView
                android:id="@+id/pur_wv_hard"
                android:layout_width="match_parent"
                android:layout_height="160dp"
                android:layout_marginLeft="6dip"
                android:layout_marginRight="6dip"
                android:layout_weight="1" />
        </LinearLayout>

**Comment by 867588763** [comment]
嵌套了两层Fragment,就出现问题了，一次fragment没问题

**Comment by 598588152** [comment]
不是LoopView的问题   你是在ViewPager中引用了LoopView，所以是ViewPager问题,重写ViewPager，参考网址：https://blog.csdn.net/com314159/article/details/41245329，https://blog.csdn.net/zhuwentao2150/article/details/52206524，试试。。
