### ISSUE TITLE
LoopView.java的onDraw方法crash崩溃

### ISSUE THREAD

**Issue by pop1030123** [weidongjian/androidWheelView#52]
LoopView.java的onDraw方法里：

    @Override
    protected void onDraw(Canvas canvas) {
        if (items == null) {
            return;
        }
        change = (int) (totalScrollY / (lineSpacingMultiplier * maxTextHeight));
        preCurrentIndex = initPosition + change % items.size();

以上代码中，if里面没有判断items的size不为0 ，导致为0时，最后一行代码对0取余报下面错误：

java.lang.ArithmeticException: divide by zero
	at com.weigan.loopview.LoopView.onDraw(LoopView.java:365)
	at android.view.View.draw(View.java:16201)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)

**Comment by gogoing1** [comment]
+1

**Comment by weidongjian** [comment]
已修复
https://github.com/weidongjian/androidWheelView/releases/tag/0.2.0
